
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author laksh
 */
public class home extends javax.swing.JFrame {
public int z=0;
    /**
     * Creates new form home
     */
    public home() {
        initComponents();
        newEmployeeBtn.setVisible(false);
        
        addFoodBtn.setVisible(false);
        
        
        addUserBtn.setVisible(false);
        closeBtn.setVisible(false);
        newEmployee.setVisible(false);
      logoutBtn.setVisible(false);
        addFood.setVisible(false);
       
        
        logout.setVisible(false);
        close.setVisible(false);
        addUser.setVisible(false);
       
        
        
        
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        Control = new javax.swing.JButton();
        newEmployeeBtn = new javax.swing.JButton();
        addFoodBtn = new javax.swing.JButton();
        addUserBtn = new javax.swing.JButton();
        closeBtn = new javax.swing.JButton();
        newEmployee = new javax.swing.JLabel();
        addFood = new javax.swing.JLabel();
        logout = new javax.swing.JLabel();
        close = new javax.swing.JLabel();
        logoutBtn = new javax.swing.JButton();
        addUser = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home.PNG"))); // NOI18N
        jLabel12.setText("jLabel12");

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home.PNG"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1366, 768));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Control.setIcon(new javax.swing.ImageIcon(getClass().getResource("/control hide and show.png"))); // NOI18N
        Control.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ControlMouseClicked(evt);
            }
        });
        Control.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ControlActionPerformed(evt);
            }
        });
        getContentPane().add(Control, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 19, -1, -1));

        newEmployeeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/new employee.png"))); // NOI18N
        newEmployeeBtn.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                newEmployeeBtnComponentShown(evt);
            }
        });
        newEmployeeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newEmployeeBtnActionPerformed(evt);
            }
        });
        getContentPane().add(newEmployeeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 19, -1, -1));

        addFoodBtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\laksh\\Documents\\Lakshana\\Clone\\Restaurant-billing-system\\Billing management system\\src\\add food.png")); // NOI18N
        addFoodBtn.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                addFoodBtnComponentShown(evt);
            }
        });
        addFoodBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addFoodBtnActionPerformed(evt);
            }
        });
        getContentPane().add(addFoodBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, -1, -1));

        addUserBtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\laksh\\Documents\\Lakshana\\Clone\\Restaurant-billing-system\\Billing management system\\src\\add user.png")); // NOI18N
        addUserBtn.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                addUserBtnComponentShown(evt);
            }
        });
        addUserBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addUserBtnActionPerformed(evt);
            }
        });
        getContentPane().add(addUserBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, -1, -1));

        closeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Close.png"))); // NOI18N
        closeBtn.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                closeBtnComponentShown(evt);
            }
        });
        closeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeBtnActionPerformed(evt);
            }
        });
        getContentPane().add(closeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 20, -1, -1));

        newEmployee.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        newEmployee.setText("New Employee");
        getContentPane().add(newEmployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 120, -1));

        addFood.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        addFood.setText("Add Food");
        getContentPane().add(addFood, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 100, -1));

        logout.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        logout.setText("Logout");
        getContentPane().add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 100, 64, -1));

        close.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        close.setText("Close");
        getContentPane().add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 100, 49, -1));

        logoutBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logout.png"))); // NOI18N
        logoutBtn.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                logoutBtnComponentShown(evt);
            }
        });
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });
        getContentPane().add(logoutBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 20, -1, -1));

        addUser.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        addUser.setText("Add User");
        getContentPane().add(addUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 100, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\laksh\\Documents\\Lakshana\\Clone\\Restaurant-billing-system\\Billing management system\\src\\home.PNG")); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1390, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ControlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ControlActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_ControlActionPerformed

    private void addUserBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addUserBtnActionPerformed
        // TODO add your handling code here:
        new addUser().setVisible(true);
        
        
    }//GEN-LAST:event_addUserBtnActionPerformed

    private void closeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeBtnActionPerformed
        // TODO add your handling code here:
        int a=JOptionPane.showConfirmDialog(null, "Do you want to close Application","Select",JOptionPane.YES_NO_OPTION);
        if(a==0)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_closeBtnActionPerformed

    private void ControlMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ControlMouseClicked
        // TODO add your handling code here:
        if(z==0)
        {
        try
        {
            Thread.sleep(250);
            newEmployeeBtn.setVisible(true);
            newEmployee.setVisible(true);
            
        } catch (Exception e) {
        }
        z=1;
        }
        else
        {
            newEmployeeBtn.setVisible(false);
       
        addFoodBtn.setVisible(false);
       
        
        addUserBtn.setVisible(false);
        closeBtn.setVisible(false);
        newEmployee.setVisible(false);
        logoutBtn.setVisible(false);
        addFood.setVisible(false);
        
        
        logout.setVisible(false);
        close.setVisible(false);
        addUser.setVisible(false);
        z=0;
        }
    }//GEN-LAST:event_ControlMouseClicked

    private void newEmployeeBtnComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_newEmployeeBtnComponentShown
        // TODO add your handling code here:
         try
        {
            Thread.sleep(250);
            addFoodBtn.setVisible(true);
            addFood.setVisible(true);
            
        } catch (Exception e) {
        }
    }//GEN-LAST:event_newEmployeeBtnComponentShown

    private void addFoodBtnComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_addFoodBtnComponentShown
        // TODO add your handling code here:
        try
        {
            Thread.sleep(250);
            addUserBtn.setVisible(true);
            addUser.setVisible(true);
           
            
        } catch (Exception e) {
        }
    }//GEN-LAST:event_addFoodBtnComponentShown

    private void addUserBtnComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_addUserBtnComponentShown
        // TODO add your handling code here:
        try
        {
            Thread.sleep(250);
            logoutBtn.setVisible(true);
           logout.setVisible(true);
           
            
        } catch (Exception e) {
        }
    }//GEN-LAST:event_addUserBtnComponentShown

    private void closeBtnComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_closeBtnComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_closeBtnComponentShown

    private void newEmployeeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newEmployeeBtnActionPerformed
        // TODO add your handling code here:
        
        new newBuyer().setVisible(true);
    }//GEN-LAST:event_newEmployeeBtnActionPerformed

    private void addFoodBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addFoodBtnActionPerformed
        // TODO add your handling code here:
        new newProduct().setVisible(true);
    }//GEN-LAST:event_addFoodBtnActionPerformed

    private void logoutBtnComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_logoutBtnComponentShown
        // TODO add your handling code here:
        try
        {
        Thread.sleep(250);
        closeBtn.setVisible(true);
        close.setVisible(true);
        }
        catch(Exception e)
        {
            
        }
    }//GEN-LAST:event_logoutBtnComponentShown

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        // TODO add your handling code here:
        int a=JOptionPane.showConfirmDialog(null,"Do you want to logout","Select",JOptionPane.YES_NO_OPTION);
        if(a==0)
        {
            setVisible(false);
            new login1().setVisible(true);
        }
    }//GEN-LAST:event_logoutBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Control;
    private javax.swing.JLabel addFood;
    private javax.swing.JButton addFoodBtn;
    private javax.swing.JLabel addUser;
    private javax.swing.JButton addUserBtn;
    private javax.swing.JLabel close;
    private javax.swing.JButton closeBtn;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel logout;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JLabel newEmployee;
    private javax.swing.JButton newEmployeeBtn;
    // End of variables declaration//GEN-END:variables
}
