import java.awt.Color;
import Project.ConnectionProvider;
import java.sql.*;
import javax.swing.JOptionPane;
import java.text.SimpleDateFormat;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author laksh
 */
public class newBuyer extends javax.swing.JFrame {

    /**
     * Creates new form newBuyer
     */
    public newBuyer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        contact = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        address = new javax.swing.JLabel();
        gender = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        contactField = new javax.swing.JTextField();
        emailField = new javax.swing.JTextField();
        addressField = new javax.swing.JTextField();
        genderField = new javax.swing.JComboBox<>();
        save = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        close = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        close1 = new javax.swing.JButton();
        name1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        empIdField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        designationField = new javax.swing.JTextField();
        salaryField = new javax.swing.JTextField();
        dateField = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\laksh\\Documents\\Lakshana\\Clone\\Restaurant-billing-system\\Billing management system\\src\\all page background image.png")); // NOI18N

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\laksh\\Documents\\Lakshana\\Clone\\Restaurant-billing-system\\Billing management system\\src\\all page background image.png")); // NOI18N
        jLabel8.setText("jLabel8");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(350, 200));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/new buyer.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 11, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 680, 12));

        contact.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        contact.setText("Contact No. ");
        getContentPane().add(contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, -1, -1));

        email.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        email.setText("Email id :");
        getContentPane().add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, -1, -1));

        address.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        address.setText("Address :");
        getContentPane().add(address, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 78, 24));

        gender.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        gender.setText("Gender :");
        getContentPane().add(gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 78, -1));

        nameField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nameField.setForeground(new java.awt.Color(153, 153, 153));
        nameField.setText("Enter name");
        nameField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nameFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nameFieldFocusLost(evt);
            }
        });
        nameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameFieldActionPerformed(evt);
            }
        });
        getContentPane().add(nameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, 250, -1));

        contactField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        contactField.setForeground(new java.awt.Color(153, 153, 153));
        contactField.setText("Enter contact No.");
        contactField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                contactFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                contactFieldFocusLost(evt);
            }
        });
        contactField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactFieldActionPerformed(evt);
            }
        });
        getContentPane().add(contactField, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, 250, -1));

        emailField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        emailField.setForeground(new java.awt.Color(153, 153, 153));
        emailField.setText("Enter email id");
        emailField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailFieldFocusLost(evt);
            }
        });
        getContentPane().add(emailField, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, 250, -1));

        addressField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        addressField.setForeground(new java.awt.Color(153, 153, 153));
        addressField.setText("Enter address");
        addressField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                addressFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                addressFieldFocusLost(evt);
            }
        });
        getContentPane().add(addressField, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 230, 250, -1));

        genderField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        genderField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Others" }));
        genderField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderFieldActionPerformed(evt);
            }
        });
        getContentPane().add(genderField, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, 250, -1));

        save.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/save.png"))); // NOI18N
        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        getContentPane().add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 130, 40));

        reset.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        reset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Reset.png"))); // NOI18N
        reset.setText("Reset");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        getContentPane().add(reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 410, 200, 40));

        close.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/close Jframe.png"))); // NOI18N
        close.setText("Close");
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });
        getContentPane().add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 410, 150, 40));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 680, 10));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\laksh\\Documents\\Lakshana\\Clone\\Restaurant-billing-system\\Billing management system\\src\\save.png")); // NOI18N
        jButton1.setText("Update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, 130, 40));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\laksh\\Documents\\Lakshana\\Clone\\Restaurant-billing-system\\Billing management system\\src\\details product1.png")); // NOI18N
        jButton2.setText("Employee Details");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 480, 200, 40));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel3.setText("New employee");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, -1, -1));

        close1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        close1.setIcon(new javax.swing.ImageIcon("C:\\Users\\laksh\\Documents\\Lakshana\\Clone\\Restaurant-billing-system\\Billing management system\\src\\delete.png")); // NOI18N
        close1.setText("Delete");
        close1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                close1ActionPerformed(evt);
            }
        });
        getContentPane().add(close1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 480, 150, 40));

        name1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        name1.setText("Name:");
        getContentPane().add(name1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 56, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Emp id :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 70, -1));

        empIdField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        empIdField.setForeground(new java.awt.Color(153, 153, 153));
        empIdField.setText("Enter empId");
        empIdField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                empIdFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                empIdFieldFocusLost(evt);
            }
        });
        empIdField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empIdFieldActionPerformed(evt);
            }
        });
        getContentPane().add(empIdField, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 97, 250, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Designation:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, 110, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Salary:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, 80, -1));

        designationField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        designationField.setForeground(new java.awt.Color(153, 153, 153));
        designationField.setText("Enter designation");
        designationField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                designationFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                designationFieldFocusLost(evt);
            }
        });
        getContentPane().add(designationField, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 290, 250, -1));

        salaryField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        salaryField.setForeground(new java.awt.Color(153, 153, 153));
        salaryField.setText("Enter salary");
        salaryField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                salaryFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                salaryFieldFocusLost(evt);
            }
        });
        getContentPane().add(salaryField, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 320, 250, -1));
        getContentPane().add(dateField, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 350, 260, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Join date:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\laksh\\Documents\\Lakshana\\Clone\\Restaurant-billing-system\\Billing management system\\src\\all page background image.png")); // NOI18N
        jLabel10.setText("jLabel10");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameFieldActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_nameFieldActionPerformed

    private void contactFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contactFieldActionPerformed

    private void nameFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameFieldFocusGained
        // TODO add your handling code here:
        if(nameField.getText().equals("Enter name"))
        {
            nameField.setText("");
            nameField.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_nameFieldFocusGained

    private void nameFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameFieldFocusLost
        // TODO add your handling code here:
        if(nameField.getText().equals(""))
        {
            nameField.setText("Enter name");
            nameField.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_nameFieldFocusLost

    private void contactFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_contactFieldFocusGained
        // TODO add your handling code here:
        if(contactField.getText().equals("Enter contact No."))
        {
            contactField.setText("");
            contactField.setForeground(new Color(0,0,0));
        }
        
    }//GEN-LAST:event_contactFieldFocusGained

    private void contactFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_contactFieldFocusLost
        // TODO add your handling code here:
        if(contactField.getText().equals(""))
        {
            contactField.setText("Enter contact No.");
            contactField.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_contactFieldFocusLost

    private void emailFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailFieldFocusGained
        // TODO add your handling code here:
         if( emailField.getText().equals("Enter email id"))
        {
             emailField.setText("");
             emailField.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_emailFieldFocusGained

    private void emailFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailFieldFocusLost
        // TODO add your handling code here:
        if( emailField.getText().equals(""))
        {
             emailField.setText("Enter email id");
             emailField.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_emailFieldFocusLost

    private void addressFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addressFieldFocusGained
        // TODO add your handling code here:
        if( addressField.getText().equals("Enter address"))
        {
             addressField.setText("");
             addressField.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_addressFieldFocusGained

    private void addressFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addressFieldFocusLost
        // TODO add your handling code here:
        if( addressField.getText().equals(""))
        {
             addressField.setText("Enter address");
            addressField.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_addressFieldFocusLost

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        
    }//GEN-LAST:event_closeActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new newBuyer().setVisible(true);
    }//GEN-LAST:event_resetActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
        String empId=empIdField.getText();
        String name=nameField.getText();
        String contact=contactField.getText();
        String email=emailField.getText();
        String address=addressField.getText();
        String gender=(String)genderField.getSelectedItem();
        String designation=designationField.getText();
        String salary=salaryField.getText();
        SimpleDateFormat sdf=new SimpleDateFormat("dd-MMM-Y");
        String date=sdf.format(dateField.getDate());
        
        int Id=Integer.parseInt(empId);
       
        
        try
        {
            Connection con=ConnectionProvider.getCon();
            Statement st=con.createStatement();
            st.executeUpdate("insert into employee values('"+Id+"','"+name+"','"+contact+"','"+email+"','"+address+"','"+gender+"','"+designation+"','"+date+"','"+salary+"')");
            System.out.println("Insert sucessfull");
            JOptionPane.showMessageDialog(null,"Succesfully Updated");
            setVisible(false);
            new newBuyer().setVisible(true);
            
        }
        catch(Exception e)
                {
                    e.printStackTrace(System.out);
                    JOptionPane.showMessageDialog(null,e);
                    
                }
        
        
        
    }//GEN-LAST:event_saveActionPerformed

    private void genderFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genderFieldActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new updateBuyer().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new buyerDetails().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void close1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_close1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new deleteBuyer().setVisible(true);
    }//GEN-LAST:event_close1ActionPerformed

    private void empIdFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empIdFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empIdFieldActionPerformed

    private void empIdFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_empIdFieldFocusGained
        // TODO add your handling code here:
        if(empIdField.getText().equals("Enter empId"))
        {
            empIdField.setText("");
            empIdField.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_empIdFieldFocusGained

    private void empIdFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_empIdFieldFocusLost
        // TODO add your handling code here:
        if( empIdField.getText().equals(""))
        {
             empIdField.setText("Enter empId ");
             empIdField.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_empIdFieldFocusLost

    private void designationFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_designationFieldFocusGained
        // TODO add your handling code here:
        if(designationField.getText().equals("Enter designation"))
        {
            designationField.setText("");
            designationField.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_designationFieldFocusGained

    private void designationFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_designationFieldFocusLost
        // TODO add your handling code here:
        if(designationField.getText().equals(""))
        {
            designationField.setText("Enter designation");
            designationField.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_designationFieldFocusLost

    private void salaryFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_salaryFieldFocusGained
        // TODO add your handling code here:
        if(salaryField.getText().equals("Enter salary"))
        {
            salaryField.setText("");
            salaryField.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_salaryFieldFocusGained

    private void salaryFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_salaryFieldFocusLost
        // TODO add your handling code here:
        if(salaryField.getText().equals(""))
        {
            salaryField.setText("Enter salary");
            salaryField.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_salaryFieldFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(newBuyer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(newBuyer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(newBuyer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(newBuyer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new newBuyer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel address;
    private javax.swing.JTextField addressField;
    private javax.swing.JButton close;
    private javax.swing.JButton close1;
    private javax.swing.JLabel contact;
    private javax.swing.JTextField contactField;
    private com.toedter.calendar.JDateChooser dateField;
    private javax.swing.JTextField designationField;
    private javax.swing.JLabel email;
    private javax.swing.JTextField emailField;
    private javax.swing.JTextField empIdField;
    private javax.swing.JLabel gender;
    private javax.swing.JComboBox<String> genderField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel name1;
    private javax.swing.JTextField nameField;
    private javax.swing.JButton reset;
    private javax.swing.JTextField salaryField;
    private javax.swing.JButton save;
    // End of variables declaration//GEN-END:variables
}
