import java.awt.Color;
import Project.ConnectionProvider;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Image;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.FileOutputStream;
import java.sql.*;
import javax.swing.JOptionPane;
import java.util.Date;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import net.proteanit.sql.DbUtils;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author laksh
 */
public class Receptionist extends javax.swing.JFrame {

    /**
     * Creates new form Receptionist
     */
    public double total_price;
    public Receptionist() {
        initComponents();
        SimpleDateFormat dFormat=new SimpleDateFormat("dd-MM-yyyy");
        Date date=new Date();
        dateField.setText(dFormat.format(date));
        
        DateTimeFormatter dtf=DateTimeFormatter.ofPattern("HH-mm-ss");
        LocalDateTime now=LocalDateTime.now();
        timeField.setText(dtf.format(now));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        dateField = new javax.swing.JLabel();
        timeField = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        customerNameField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        phoneNoField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        orderIdField = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        totalField = new javax.swing.JTextField();
        paidField = new javax.swing.JTextField();
        returnField = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        orderTable = new javax.swing.JTable();
        generateBillBtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(330, 160));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Billing ani.gif"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 11, 299, 90));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Date");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 30, 55, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Time");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 65, 44, -1));

        dateField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        dateField.setText("jLabel5");
        getContentPane().add(dateField, new org.netbeans.lib.awtextra.AbsoluteConstraints(917, 30, 120, -1));

        timeField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        timeField.setText("jLabel6");
        getContentPane().add(timeField, new org.netbeans.lib.awtextra.AbsoluteConstraints(917, 65, 140, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/billing.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 11, 73, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 107, 1047, 10));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Customer name");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 138, -1, -1));

        customerNameField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        customerNameField.setForeground(new java.awt.Color(153, 153, 153));
        customerNameField.setText("Enter customer Name");
        customerNameField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                customerNameFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                customerNameFieldFocusLost(evt);
            }
        });
        getContentPane().add(customerNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(263, 135, 180, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Phone No.");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 179, 114, -1));

        phoneNoField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        phoneNoField.setForeground(new java.awt.Color(153, 153, 153));
        phoneNoField.setText("Enter phone No.");
        phoneNoField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                phoneNoFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                phoneNoFieldFocusLost(evt);
            }
        });
        getContentPane().add(phoneNoField, new org.netbeans.lib.awtextra.AbsoluteConstraints(263, 176, 180, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Order Id");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 225, 87, -1));

        orderIdField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        orderIdField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderIdFieldActionPerformed(evt);
            }
        });
        getContentPane().add(orderIdField, new org.netbeans.lib.awtextra.AbsoluteConstraints(263, 222, 180, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setText("Calculation Details:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 265, 193, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("Total(Including Tax): ");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 170, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText("Paid amount:");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 373, -1, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setText("Return amount:");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 421, 150, -1));

        totalField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        totalField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalFieldActionPerformed(evt);
            }
        });
        getContentPane().add(totalField, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 319, 137, -1));

        paidField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        paidField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paidFieldActionPerformed(evt);
            }
        });
        getContentPane().add(paidField, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 360, 137, -1));

        returnField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        returnField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnFieldActionPerformed(evt);
            }
        });
        getContentPane().add(returnField, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 418, 137, -1));

        orderTable.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        orderTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        jScrollPane2.setViewportView(orderTable);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(469, 129, 571, 158));

        generateBillBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        generateBillBtn.setText("Generate Bill");
        generateBillBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateBillBtnActionPerformed(evt);
            }
        });
        getContentPane().add(generateBillBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(469, 322, -1, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\laksh\\Documents\\Lakshana\\Clone\\Restaurant-billing-system\\Billing management system\\src\\Reset.png")); // NOI18N
        jButton1.setText("Reset");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(469, 365, 125, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\laksh\\Documents\\Lakshana\\Clone\\Restaurant-billing-system\\Billing management system\\src\\close Jframe.png")); // NOI18N
        jButton2.setText("Close");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(469, 415, 125, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\laksh\\Documents\\Lakshana\\Clone\\Restaurant-billing-system\\Billing management system\\src\\billing background.png")); // NOI18N
        jLabel9.setText("jLabel9");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 1060, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void customerNameFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_customerNameFieldFocusGained
        // TODO add your handling code here:
        if(customerNameField.getText().equals("Enter customer Name"))
        {
            customerNameField.setText("");
            customerNameField.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_customerNameFieldFocusGained

    private void customerNameFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_customerNameFieldFocusLost
        // TODO add your handling code here:
        if(customerNameField.getText().equals(""))
        {
            customerNameField.setText("Enter customer Name");
            customerNameField.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_customerNameFieldFocusLost

    private void phoneNoFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_phoneNoFieldFocusGained
        // TODO add your handling code here:
        if(phoneNoField.getText().equals("Enter phone No."))
        {
            phoneNoField.setText("");
            phoneNoField.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_phoneNoFieldFocusGained

    private void phoneNoFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_phoneNoFieldFocusLost
        // TODO add your handling code here:
        if(phoneNoField.getText().equals(""))
        {
            phoneNoField.setText("Enter phone No.");
            phoneNoField.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_phoneNoFieldFocusLost

    private void totalFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalFieldActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_totalFieldActionPerformed

    private void paidFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paidFieldActionPerformed
        // TODO add your handling code here:
        String paidAmt=paidField.getText();
        String total_price=totalField.getText();
        float returnAmt=Float.parseFloat(paidAmt)-Float.parseFloat(total_price);
        returnField.setText(String.valueOf(returnAmt));
        returnField.setEditable(false);
        totalField.setEditable(false);

    }//GEN-LAST:event_paidFieldActionPerformed

    private void returnFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnFieldActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_returnFieldActionPerformed

    private void orderIdFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderIdFieldActionPerformed
        // TODO add your handling code here:
        try
        {
        String orderId=orderIdField.getText();
        Connection con=ConnectionProvider.getCon();
        Statement st=con.createStatement();
        ResultSet rs=st.executeQuery("select food_id,food_name,price,quantity,total_price from order_place where order_id='"+orderId+"'");
        orderTable.setModel(DbUtils.resultSetToTableModel(rs));
        ResultSet rs1=st.executeQuery("select sum(total_price) from order_place where order_id='"+orderId+"' group by '"+orderId+"'");
        if(rs1.next())
        {
            total_price=Double.parseDouble(rs1.getString(1));
            double sgst=total_price*0.025;
            double cgst=sgst;
            double total=total_price+sgst+sgst;
            totalField.setText(String.valueOf(total));
            
        }
        
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
        
        
    }//GEN-LAST:event_orderIdFieldActionPerformed

    private void generateBillBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateBillBtnActionPerformed
        // TODO add your handling code here:
        String name=customerNameField.getText();
         String path="D:\\";
         com.itextpdf.text.Document doc=new com.itextpdf.text.Document();
         String tot=totalField.getText();
         double sgst=total_price*0.025;
         double cgst=sgst;
         
         
  
         String cphone=phoneNoField.getText();
         
        try
        {
            int i;
           PdfWriter.getInstance(doc,new FileOutputStream(path+""+name+" "+dateField.getText()+" "+".pdf"));
           doc.open();  
           path="C:/Users/laksh/OneDrive/Documents/spiceDelight.jpeg/";
           Image image=Image.getInstance(path);
           doc.add(image);   
           Paragraph para1=new Paragraph("                                             The Spice Delight\n                            ",FontFactory.getFont(FontFactory.TIMES_BOLD,18));
           doc.add(para1);
           Paragraph para2=new Paragraph("___________________________________________________________________________");
           doc.add(para2);
           Paragraph para3=new Paragraph("Customer Details\n",FontFactory.getFont(FontFactory.TIMES_BOLD,18));
           doc.add(para3);
           
           Paragraph para4=new Paragraph("Name: "+name+"\n"+"Phone No: "+cphone+"\n"+"Date : "+dateField.getText()+"\nTime : "+timeField.getText()+"\n");
           doc.add(para4);
           doc.add(para2);
           Paragraph para5=new Paragraph("Order Details\n\n",FontFactory.getFont(FontFactory.TIMES_BOLD,18));
           doc.add(para5);
           PdfPTable tb=new PdfPTable(4);
           tb.addCell("Name");
           tb.addCell("Price");
           tb.addCell("Quantity");
           tb.addCell("Total Price");
           for(i=0;i<orderTable.getRowCount();i++)
           {
               String n=orderTable.getValueAt(i, 1).toString();
               String p=orderTable.getValueAt(i, 2).toString();
               String q=orderTable.getValueAt(i, 3).toString();
               String t=orderTable.getValueAt(i, 4).toString();
               
               tb.addCell(n);
               tb.addCell(p);
               tb.addCell(q);
               tb.addCell(t);
               
           }
           doc.add(tb);
           Paragraph para6=new Paragraph("\nSub total: Rs "+total_price+"\nSGST@2.5%: "+sgst+"%\n"+"CGST@2.5%: "+cgst+"%\n");
           
//+"Total amount"+totalToBepaid+"\nPaid amount: "+paidField.getText()+"\nReturn amount: "+returnField.getText()+"\n\n Thank you");
           doc.add(para6);
           doc.add(para2);
           Paragraph para7=new Paragraph("Total amount: Rs "+totalField.getText(),FontFactory.getFont(FontFactory.TIMES_BOLD,15));
           doc.add(para7);
           Paragraph para8=new Paragraph("Paid amount: Rs "+paidField.getText(),FontFactory.getFont(FontFactory.TIMES_BOLD,15));
           doc.add(para8);
           Paragraph para9=new Paragraph("Return amount: Rs "+returnField.getText(),FontFactory.getFont(FontFactory.TIMES_BOLD,15));
           doc.add(para9);
           doc.add(para2);
           
           JOptionPane.showMessageDialog(null,"Bill Generated");
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
        doc.close();
    }//GEN-LAST:event_generateBillBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new Receptionist().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Receptionist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Receptionist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Receptionist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Receptionist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Receptionist().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField customerNameField;
    private javax.swing.JLabel dateField;
    private javax.swing.JButton generateBillBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField orderIdField;
    private javax.swing.JTable orderTable;
    private javax.swing.JTextField paidField;
    private javax.swing.JTextField phoneNoField;
    private javax.swing.JTextField returnField;
    private javax.swing.JLabel timeField;
    private javax.swing.JTextField totalField;
    // End of variables declaration//GEN-END:variables
}
