import java.sql.*;
import Project.ConnectionProvider;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author laksh
 */
public class updateBuyer extends javax.swing.JFrame {

    /**
     * Creates new form updateBuyer
     */
    public updateBuyer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        salaryField1 = new javax.swing.JTextField();
        salaryField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        empIdField = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        search = new javax.swing.JButton();
        update = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        close = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        name1 = new javax.swing.JLabel();
        contact = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        address = new javax.swing.JLabel();
        gender = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        contactField = new javax.swing.JTextField();
        emailField = new javax.swing.JTextField();
        addressField = new javax.swing.JTextField();
        genderField = new javax.swing.JTextField();
        designationField = new javax.swing.JTextField();
        salaryField = new javax.swing.JTextField();
        dateField = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/all page background image.png"))); // NOI18N
        jLabel4.setText("jLabel4");

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/all page background image.png"))); // NOI18N
        jLabel10.setText("jLabel10");

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\laksh\\Documents\\Lakshana\\Clone\\Restaurant-billing-system\\Billing management system\\src\\all page background image.png")); // NOI18N

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\laksh\\Documents\\Lakshana\\Clone\\Restaurant-billing-system\\Billing management system\\src\\all page background image.png")); // NOI18N
        jLabel8.setText("jLabel8");

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\laksh\\Documents\\Lakshana\\Clone\\Restaurant-billing-system\\Billing management system\\src\\all page background image.png")); // NOI18N
        jLabel9.setText("jLabel9");

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\laksh\\Documents\\Lakshana\\Clone\\Restaurant-billing-system\\Billing management system\\src\\all page background image.png")); // NOI18N
        jLabel11.setText("jLabel11");

        salaryField1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        salaryField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salaryField1ActionPerformed(evt);
            }
        });

        salaryField2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        salaryField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salaryField2ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(380, 160));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Update buyer.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 11, 60, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 77, 580, 11));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Emp ID");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, -1, -1));

        empIdField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        empIdField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empIdFieldActionPerformed(evt);
            }
        });
        getContentPane().add(empIdField, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, 151, -1));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 152, 580, 10));

        search.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/search.png"))); // NOI18N
        search.setText("Search");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        getContentPane().add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 110, -1, -1));

        update.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/save.png"))); // NOI18N
        update.setText("Update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        getContentPane().add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 480, -1, -1));

        reset.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        reset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Reset.png"))); // NOI18N
        reset.setText("Reset");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        getContentPane().add(reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 480, 102, -1));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 449, 580, 10));

        close.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/close Jframe.png"))); // NOI18N
        close.setText("Close");
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });
        getContentPane().add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 480, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel12.setText("Update Employee");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, -1, -1));

        name1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        name1.setText("Name:");
        getContentPane().add(name1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 56, -1));

        contact.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        contact.setText("Contact No. ");
        getContentPane().add(contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, -1, -1));

        email.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        email.setText("Email id :");
        getContentPane().add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, -1, -1));

        address.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        address.setText("Address :");
        getContentPane().add(address, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, 78, 24));

        gender.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        gender.setText("Gender :");
        getContentPane().add(gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, 78, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Designation:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, 110, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Salary:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 380, 80, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Join date:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 410, -1, -1));

        nameField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameFieldActionPerformed(evt);
            }
        });
        getContentPane().add(nameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, 250, -1));

        contactField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        contactField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactFieldActionPerformed(evt);
            }
        });
        getContentPane().add(contactField, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, 250, -1));

        emailField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        emailField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailFieldActionPerformed(evt);
            }
        });
        getContentPane().add(emailField, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, 250, -1));

        addressField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        addressField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressFieldActionPerformed(evt);
            }
        });
        getContentPane().add(addressField, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 280, 250, -1));

        genderField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        genderField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderFieldActionPerformed(evt);
            }
        });
        getContentPane().add(genderField, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 310, 250, -1));

        designationField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        designationField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                designationFieldActionPerformed(evt);
            }
        });
        getContentPane().add(designationField, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 340, 250, -1));

        salaryField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        salaryField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salaryFieldActionPerformed(evt);
            }
        });
        getContentPane().add(salaryField, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 380, 250, -1));

        dateField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        dateField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateFieldActionPerformed(evt);
            }
        });
        getContentPane().add(dateField, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 410, 250, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon("C:\\Users\\laksh\\Documents\\Lakshana\\Clone\\Restaurant-billing-system\\Billing management system\\src\\all page background image.png")); // NOI18N
        jLabel13.setText("jLabel13");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void empIdFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empIdFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empIdFieldActionPerformed

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new newBuyer().setVisible(true);
        
    }//GEN-LAST:event_closeActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new updateBuyer().setVisible(true);
    }//GEN-LAST:event_resetActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
        String topEmpid=empIdField.getText();
        String name=nameField.getText();
        String contact=contactField.getText();
        String email=emailField.getText();
        String address=addressField.getText();
        String gender=genderField.getText();
        String designation=designationField.getText();
        String salary=salaryField.getText();
        String date=dateField.getText();
        try
        {
            Connection con=ConnectionProvider.getCon();
        Statement st=con.createStatement();
        st.executeUpdate("update employee set name='"+name+"',phone_no='"+contact+"',email='"+email+"',address='"+address+"',gender='"+gender+"',designation='"+designation+"',join_date='"+date+"',salary='"+salary+"' where emp_id='"+topEmpid+"'" );
        JOptionPane.showMessageDialog(null,"Updated sucessfully");
        setVisible(false);
        new updateBuyer().setVisible(true);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_updateActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
        String id=empIdField.getText();
        try{
        Connection con=ConnectionProvider.getCon();
        Statement st=con.createStatement();
        ResultSet rs=st.executeQuery("select * from employee where emp_id='"+id+"'");
        if(rs.next())
        {
            nameField.setText(rs.getString(2));
            contactField.setText(rs.getString(3));
            emailField.setText(rs.getString(4));
            addressField.setText(rs.getString(5));
            genderField.setText(rs.getString(6));
            designationField.setText(rs.getString(7));
            dateField.setText(rs.getString(8));
            salaryField.setText(rs.getString(9));
            
        }
        else
        {
            JOptionPane.showMessageDialog(null,"Employee Id does not exist");
            setVisible(false);
            new updateBuyer().setVisible(true);
        }
         }
        
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_searchActionPerformed

    private void nameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameFieldActionPerformed

    private void contactFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contactFieldActionPerformed

    private void emailFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailFieldActionPerformed

    private void addressFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressFieldActionPerformed

    private void genderFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genderFieldActionPerformed

    private void designationFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_designationFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_designationFieldActionPerformed

    private void salaryFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salaryFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_salaryFieldActionPerformed

    private void salaryField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salaryField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_salaryField1ActionPerformed

    private void salaryField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salaryField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_salaryField2ActionPerformed

    private void dateFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(updateBuyer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(updateBuyer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(updateBuyer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(updateBuyer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new updateBuyer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel address;
    private javax.swing.JTextField addressField;
    private javax.swing.JButton close;
    private javax.swing.JLabel contact;
    private javax.swing.JTextField contactField;
    private javax.swing.JTextField dateField;
    private javax.swing.JTextField designationField;
    private javax.swing.JLabel email;
    private javax.swing.JTextField emailField;
    private javax.swing.JTextField empIdField;
    private javax.swing.JLabel gender;
    private javax.swing.JTextField genderField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel name1;
    private javax.swing.JTextField nameField;
    private javax.swing.JButton reset;
    private javax.swing.JTextField salaryField;
    private javax.swing.JTextField salaryField1;
    private javax.swing.JTextField salaryField2;
    private javax.swing.JButton search;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
